Kooo1225/SportyLight

src/main/java/com/sportylight/domain/GatherVO.java
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/resources/js/home/homeAjax.js

Fix Base Project for Dev Branch

Fix Base Project

---

src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/domain/EnumVO.java
src/main/java/com/sportylight/domain/MemberVO.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/webapp/WEB-INF/views/layouts/joinHeader.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/join/join.css

- EnumVO에서 male, female 추가 memberVO에서 데이터타입 EnumVO로 변환
- email중복확인, password 확인 여부 기능을 위한 SecurityController 생성
- 회원가입 register를 구현하기 위한 MemberMapper안에 insert, MemberService에 get, register 생성
- MemberMapper.xml 부분 추가
- 정상적인 동작을 위해 join.jsp 수정 필요
- avatar생성을 위해 추후에 추가작업이 필요함
- emailCheck(실시간 이메일 중복확인)기능 추후에 고려..주석처리
- /security/join.jsp 및 /css/join.css 정현이가 보내준 파일에서 수정 및 추가

feat(join) : 회원가입 정보 데이터베이스로 전달, 에러메시지 view부분 뜨게함(수정 필요)

---

src/main/java/com/sportylight/controller/BoardController.java
src/main/java/com/sportylight/mapper/GatherMapper.java
src/main/java/com/sportylight/service/GatherService.java
src/main/java/com/sportylight/service/GatherServiceImpl.java
src/main/resources/com/sportylight/mapper/GatherMapper.xml
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/register.jsp
src/main/webapp/WEB-INF/views/layouts/detailHeader.jsp
src/main/webapp/WEB-INF/views/layouts/registerHeader.jsp
src/main/webapp/resources/css/layouts/common.css

- GatherVO에서 LocalDateTime 타입 수정
- register, detail 로직을 처리하기 위한 BoardController 생성
- register, detail Service를 구현하기 위한 Mapper, Service 로직 생성
- GatheringMapper.xml 부분 추가
- /Board/register.jsp 및 /Board/detail.jsp 페이지 작성
- 정상적인 동작을 위해 home.jsp 수정 필요
- RootConfig의 JDBC 연결 변환 필요
- sport 하위 카테고리 삭제

feat(register, detail) : 최종 Base Project에서 register 및 detail 페이지 구현

---

src/main/java/com/sportylight/controller/MemberController.java
src/main/java/com/sportylight/domain/MemberVO.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/layouts/mpheader.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp
src/main/webapp/WEB-INF/views/mypage/mypageupdate.jsp
src/main/webapp/WEB-INF/views/mypage/withdrawl.jsp
src/main/webapp/resources/css/mypage/mypage.css

mypage 를 구현하기 위한 Mapper, Service  메소드 생성
MemberMapper.xml  추가
/mypage.jsp, /mypage/update.jsp, /mypage/withdrawl.jsp  페이지 작성 정상적인 동작을 위해 /mypage/update.jsp, /mypage/withdrawl.jsp 와 MemberController 수정 필요 /mypage/update.jsp 비밀번호 변경 시 현재 비밀번호 추가 필요
/mypage/withdrawl.jsp 디자인 변경 예정

mypage 로직을 처리하기 위한 MemberController 생성 - SecurityController 로 옮길 예정

---

src/main/java/com/sportylight/config/SecurityConfig.java
src/main/java/com/sportylight/config/Securityinitializer.java
src/main/java/com/sportylight/config/WebConfig.java
src/main/java/com/sportylight/controller/MemberController.java
src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/domain/AuthVO.java
src/main/java/com/sportylight/domain/MemberVO.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/security/CustomUserDetailsService.java
src/main/java/com/sportylight/security/domain/CustomUser.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/layouts/homeHeader.jsp
src/main/webapp/WEB-INF/views/layouts/joinHeader.jsp
src/main/webapp/WEB-INF/views/layouts/registerHeader.jsp
src/main/webapp/WEB-INF/views/security/login.jsp
src/main/webapp/WEB-INF/views/security/logout.jsp
src/main/webapp/resources/css/join/join.css
src/main/webapp/resources/css/layouts/main.css
src/test/java/com/sportylight/mapper/MemberMapperTest.java
src/test/java/com/sportylight/security/PasswordEncoderTests.java

- Encoder 된 password 저장 구현
- 로그인 된 회원 정보 출력
- home.jsp에서 detail 페이지 링크 추가
- remember-me 기능 수정 필요

feat(login) :  login 기능 구현

---

src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/layouts/homeHeader.jsp
src/main/webapp/WEB-INF/views/layouts/joinHeader.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/join/join.css

- MemberMapper.xml 부분 checkEmail과 checkNickname 추가 및 수정
- 이메일, 닉네임 중복확인 작동 확인완료
- 이메일, 닉네임 에러메시지 작동 확인완료
- MemberService, MemberServiceImpl에 checkEmail, checkNickname 추가 및 수정
- ServiceController에 이메일, 닉네임 중복확인 코드 추가 및 수정

feat(join) : join 기능 수정

---

src/main/java/com/sportylight/mapper/MemberMapper.java

feat(join) : MemberMapper 수정

---

src/main/java/com/sportylight/mapper/MemberMapper.java

박홍근씨의 1번 실수로 인한 리버트

---

src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/layouts/homeHeader.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/join/join.css

박홍근씨의 2번 실수로 인한 리버트

---

src/main/java/com/sportylight/config/SecurityConfig.java
src/main/java/com/sportylight/controller/MessageController.java
src/main/webapp/WEB-INF/views/chat.jsp
src/main/webapp/WEB-INF/views/security/login.jsp
src/main/webapp/resources/css/join/join.css
src/test/java/com/sportylight/mapper/ChattingMapperTest.java

Fix feat-chat

---

src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/register.jsp
src/main/webapp/WEB-INF/views/layouts/homeHeader.jsp

- register 시에 membersId를 hidden 처리한 임시값을 실제 등록한 membersId로 등록처리
- detail 페이지에 자신이 등록한 모임들에는 '신청' 버튼 대신 '관리' 버튼으로 대체

feat(detail v2) : detail v2

---

src/main/java/com/sportylight/domain/GatherVO.java
src/main/resources/com/sportylight/mapper/GatherMapper.xml
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/home/home.jsp

- 오버레이 마커에 현재 모임 신청 인원 표기
- 모집인원 == 신청인원 시 오버레이에서 '모임신청' 링크 -> '모임마감'으로 변경
- detail 페이지에 현재 신청인원 표시, 마커 이미지 수정
- 모집인원 == 신청인원 시 사이드바에서 '모임신청' 링크 -> '모임마감'으로 변경

feat(detail v3) : detail v3

---

src/main/java/com/sportylight/controller/MemberController.java
src/main/java/com/sportylight/domain/MemberVO.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/mypage/mypage.jsp
src/main/webapp/WEB-INF/views/mypage/mypageupdate.jsp
src/main/webapp/WEB-INF/views/mypage/pwupdate.jsp
src/main/webapp/resources/css/mypage/mypage.css

feat-mypage. jsp
성별 선택 가능 남/여로 이름 변경
프로필 사진 변경

Feat-mypage

---

src/main/java/com/sportylight/config/SecurityConfig.java
src/main/java/com/sportylight/controller/MemberController.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/MemberService.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/resources/com/sportylight/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp
src/main/webapp/WEB-INF/views/mypage/mypageupdate.jsp
src/main/webapp/resources/css/home/home.css
src/main/webapp/resources/css/mypage/mypage.css

feat-mypage,home.jsp
프로필 사진 조회,변경에 프로필 사진 처리 완료
마이페이지 프로필 사진 변경 완료
홈 사이드바 css 변경

Feat mypage

---

src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp
src/main/webapp/resources/css/home/home.css

feat(search v2) : 검색창 디자인 수정

---

src/main/java/com/sportylight/controller/BoardAjaxController.java
src/main/java/com/sportylight/controller/BoardController.java
src/main/java/com/sportylight/mapper/GatherMapper.java
src/main/java/com/sportylight/service/GatherService.java
src/main/java/com/sportylight/service/GatherServiceImpl.java
src/main/resources/com/sportylight/mapper/GatherMapper.xml
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/mylist.jsp
src/main/webapp/resources/css/board/mylist.css
src/main/webapp/resources/css/security/join.css
src/main/webapp/resources/js/board/boardAjax.js

- 신청하기 구현완료 : 신청 누르면 신청완료로 바뀜
- 나의 목록 css 변경

feat-apply

---

src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/service/MemberServiceImpl.java
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/register.jsp
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/board/detail.css

- 관리 버튼 클릭 시 모임수정, 인원관리 버튼 출력
- 회원가입 시 미래 날짜 선택 불가
- 모임등록 시 과거 날짜 선택 불가

feat(design) : 디자인 수정

---

pom.xml
src/main/java/com/sportylight/config/EmailConfig.java
src/main/java/com/sportylight/config/ServletConfig.java

fix-feat-email

---

src/main/webapp/resources/js/board/boardAjax.js

fix-feat-list

---

src/main/java/com/sportylight/controller/ContestController.java
src/main/java/com/sportylight/domain/ContestVO.java
src/main/java/com/sportylight/mapper/ContestMapper.java
src/main/java/com/sportylight/service/ContestService.java
src/main/java/com/sportylight/service/ContestServiceImpl.java
src/main/resources/com/sportylight/mapper/ContestMapper.xml
src/main/webapp/WEB-INF/views/contest/list.jsp
src/test/java/com/sportylight/mapper/ContestMapperTest.java

- contestVO
- contetestMapper, contestMapper.xml
- contestService, contestServiceImpl
- /contest/list.jsp 생성 (미완성)

feat(contest) : 대회 mvc 패턴 생성

---

src/main/java/com/sportylight/controller/HomeAjaxController.java
src/main/java/com/sportylight/mapper/GatherMapper.java
src/main/java/com/sportylight/service/GatherService.java
src/main/java/com/sportylight/service/GatherServiceImpl.java
src/main/resources/com/sportylight/mapper/GatherMapper.xml
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/security/join2.css
src/test/java/com/sportylight/service/GatherServiceTest2.java

* 사용자 위치 중심으로 모임 출력 기능 추가
* 위 사항 적용을 위한 Mapper, Service 추가
* Home.jsp 접속 시 기존 동기 처리 비동기 처리로 변경

Fix feat-home

---

src/main/java/com/sportylight/controller/HomeController.java
src/main/java/com/sportylight/mapper/GatherMapper.java
src/main/java/com/sportylight/service/GatherService.java
src/main/java/com/sportylight/service/GatherServiceImpl.java
src/main/resources/com/sportylight/mapper/GatherMapper.xml
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/layouts/homeHeader.jsp

- 신청인원이 1명 남은 모임글 topic 모임글로 출력
- 미완성...

feat(topic) : home.jsp에서 topic 모임글 출력

---

src/main/java/com/sportylight/controller/HomeAjaxController.java
src/main/java/com/sportylight/controller/MailController.java
src/main/java/com/sportylight/controller/MemberController.java
src/main/java/com/sportylight/controller/SecurityController.java
src/main/java/com/sportylight/domain/CategoryEnumVO.java
src/main/java/com/sportylight/domain/EnumVO.java
src/main/java/com/sportylight/domain/GatherVO.java
src/main/java/com/sportylight/domain/GenderEnumVO.java
src/main/java/com/sportylight/domain/MemberVO.java
src/main/java/com/sportylight/mapper/GatherMapper.java
src/main/java/com/sportylight/mapper/MemberMapper.java
src/main/java/com/sportylight/service/GatherService.java
src/main/java/com/sportylight/service/GatherServiceImpl.java
src/main/webapp/WEB-INF/views/home/home.jsp
src/main/webapp/WEB-INF/views/security/join.jsp
src/main/webapp/resources/css/home/home.css
src/test/java/com/sportylight/mapper/GatherMapperTest.java
src/test/java/com/sportylight/service/GatherServiceTest2.java

* 이메일 인증 구현 완료
* 메인 페이지 모임 리스트 지역 카테고리 추가 완료

fix feat-join

---

src/main/webapp/WEB-INF/views/contest/list.jsp
src/main/webapp/resources/css/contest/contest.css

feat(contest v2) : contest 디자인 수정
